const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/routes/index-route.js',
                        './src/routes/jsonFileUpload-route.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "NodeJsonFile",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: [
        'http', 'https'
    ],
    consumes: ['application/json'],
    produces: ['application/json']
    }

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./bin/www')
})
